export const ActionTypes = {
  SET_HOUSES: "SET_HOUSES",
  SELECTED_HOUSES: "SELECTED_HOUSES",
  REMOVE_SELECTED_HOUSES: "REMOVE_SELECTED_HOUSES",
  NEXT_PAGE: "NEXT_PAGE",
  PREV_PAGE: "PREVIOUS_PAGE",
};
